# Generated by Django 3.1.3 on 2021-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight_In_Kg', models.IntegerField(null=True)),
                ('Height_In_CM', models.IntegerField(null=True)),
                ('Group', models.IntegerField(null=True)),
                ('Grade', models.IntegerField(null=True)),
                ('Category', models.CharField(max_length=6)),
            ],
        ),
    ]
