# Generated by Django 3.1.3 on 2021-06-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Height_In_CM',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Weight_In_Kg',
        ),
        migrations.AddField(
            model_name='test',
            name='eight',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='eleven',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='fifteen',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='five',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='four',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='fourteen',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='nine',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='one',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='seven',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='six',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='ten',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='thirteen',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='three',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='tweleve',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='two',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
