# Generated by Django 3.1.3 on 2021-06-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20210615_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='eight',
            new_name='c1',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='eleven',
            new_name='c10',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='fifteen',
            new_name='c11',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='five',
            new_name='c12',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='four',
            new_name='c13',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='fourteen',
            new_name='c14',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='nine',
            new_name='c15',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='one',
            new_name='c2',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='seven',
            new_name='c3',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='six',
            new_name='c4',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='ten',
            new_name='c5',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='thirteen',
            new_name='c6',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='three',
            new_name='c7',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='tweleve',
            new_name='c8',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='two',
            new_name='c9',
        ),
    ]
