# Generated by Django 3.1.3 on 2021-06-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20210615_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='c1',
            new_name='c16',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c2',
            new_name='c17',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c3',
            new_name='c18',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c4',
            new_name='c19',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c5',
            new_name='c20',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c6',
            new_name='c21',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c7',
            new_name='c22',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c8',
            new_name='c23',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='c9',
            new_name='c24',
        ),
    ]
