# Generated by Django 3.1.3 on 2021-06-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20210615_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='c16',
        ),
    ]
